# Generated by Django 5.1.4 on 2025-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
